#!/usr/bin/env bash
# install.sh RAILS_APP_ROOT — drop the sticky-notes Stimulus controller + partial into a Rails app.
# Controller is self-contained (core inlined) and loads in development + staging only:
#   importmap → app/javascript/dev/sticky_notes_controller.js, pinned under the env condition
#   vite      → <sourceCodeDir>/entrypoints/sticky_notes.js, tagged only when the partial renders
set -euo pipefail
app=${1:?usage: install.sh RAILS_APP_ROOT}
here=$(dirname "$(readlink -f "$0")")
partial=$app/app/views/application/_sticky_notes.html.erb
importmap=$app/config/importmap.rb
env_cond='Rails.env.development? || Rails.env.staging?'

if [ -f "$importmap" ]; then
  ctrl=$app/app/javascript/dev/sticky_notes_controller.js
  app_import="controllers/application"
  script_tag='javascript_import_module_tag "dev/sticky_notes_controller"'
elif [ -f "$app/config/vite.json" ]; then
  src=$(python3 -c 'import json,sys; print(json.load(open(sys.argv[1]))["all"].get("sourceCodeDir","app/frontend"))' "$app/config/vite.json")
  ctrl=$app/$src/entrypoints/sticky_notes.js
  app_import="../controllers/application"
  script_tag='vite_javascript_tag "sticky_notes"'
else
  echo "neither config/importmap.rb nor config/vite.json in $app" >&2; exit 1
fi

mkdir -p "$(dirname "$ctrl")" "$(dirname "$partial")"
{
  echo "// generated by ~/.claude/skills/sticky-notes/rails/install.sh — edit the skill, re-run, do not hand-edit"
  echo 'import { Controller } from "@hotwired/stimulus"'
  echo
  cat "$here/../sticky-notes.js"
  sed "s|__APP_IMPORT__|$app_import|" "$here/controller.js"
} > "$ctrl"
sed "s|__SCRIPT_TAG__|$script_tag|" "$here/_sticky_notes.html.erb" > "$partial"
echo "wrote ${ctrl#$app/}"
echo "wrote ${partial#$app/}"

if [ -f "$importmap" ] && ! grep -q 'dev/sticky_notes_controller' "$importmap"; then
  printf '\n%s\n' "pin \"dev/sticky_notes_controller\" if $env_cond   # review overlay, see app/views/application/_sticky_notes.html.erb" >> "$importmap"
  echo "pinned in config/importmap.rb"
fi
cat <<MSG
next: layout, before </body>:   <%= render "sticky_notes" %>
      (per-template notes instead of per-URL: <%= render "sticky_notes", key: "#{controller_path}##{action_name}" %>)
MSG
